# .github/workflows/ci.yml
name: CI Pipeline

# This workflow runs on every push or pull request
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - uses: actions/checkout@v4
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Step 4: Train the model
      - name: Train Model
        run: python src/model.py  # This will generate iris_model.pkl
      
      # Step 5: Run the tests
      - name: Run tests
        run: pytest src/test_model.py
