name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and setuptools
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model & Generate Reports
        run: python src/model.py  # This generates assets/confusion_matrix.png and metrics.txt

      - name: Ensure docs directory exists
        run: mkdir -p docs

      - name: Move assets to docs (Ensure GitHub Pages Serves Them)
        run: |
          mv assets/* docs/

      - name: List 'docs' Directory (Debugging)
        run: ls -la docs

      - name: Publish to GitHub Pages (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Deploy updated reports to GitHub Pages"
          branch: main
          file_pattern: docs/**
          push_options: '--force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure default token is used
