name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: List 'docs' Directory (Debugging)
        run: ls -la docs

      - name: Publish to GitHub Pages (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated GitHub Pages deployment"
          branch: main
          file_pattern: docs/**
          push_options: '--force'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
