name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs
          artifact_name: github-pages  # explicitly name the artifact
      
      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # tell deploy step which artifact to use
