name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use v3 explicitly
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # Debug step to check contents of 'docs'
      - name: List 'docs' Directory
        run: ls -la docs
      
      - name: Upload Pages Artifact
        uses: actions/upload-artifact@v3  # Explicitly using v3
        with:
          path: docs
          name: github-pages  # Ensure artifact name matches

      - name: Deploy Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
