name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # Optional: Debug step to confirm the 'docs' folder is present
      - name: List 'docs' Directory
        run: ls -la docs
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs           # Ensure this is the correct folder with your site content
          artifact_name: github-pages  # Explicit artifact name
      
      - name: Deploy Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Must match the name above
