# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

# This workflow runs when there is a push to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
      
      # Step 2: Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # Step 3: Upload the 'docs' folder as the Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs
      
      # Step 4: Deploy the Pages site
      - name: Deploy
        uses: actions/deploy-pages@v2
